
 const UP_ACTION = "UP_ACTION"
 const DOWN_ACTION = "DOWN_ACTION"
 const RESET_ACTION = "RESET_ACTION"
 const RANDOM_ACTION = "RANDOM_ACTION"
 const UPDATE_ACTION = "UPDATE_ACTION"
 const MATH_ACTION = "MATH_ACTION"
export{
  UP_ACTION ,
  DOWN_ACTION ,
  RESET_ACTION ,
  RANDOM_ACTION ,
  UPDATE_ACTION,
  MATH_ACTION
}